### PR TITLE
Adding my hanoi tower

### PR DESCRIPTION
**Pull request by NinjaBob123**
My current hanoi tower. will be pushing more updates. also open discussions. tutorial here https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository

### CODE REVIEW

**Comment by NinjaBob123** [comment]
Caleb, I will be missing this weeks class, so I am going to attempt to finish my Hanoi tower code before this weeks class. I will be vacaying, so it might not happen, but I will be pushing updates every so often. Thanks. also _**OPEN DISCUSSIONS**_.
Thank you.
Hunter.

**Comment by NinjaBob123** [comment]
I am going to push again around 430 becuz that's when I get home.

**Comment by NinjaBob123** [comment]
I'm in advisory rn. And bored. and have updates at home, so can't edit. Talk to meeeeee.

**Comment by aremyarmsonmyhead** [comment]
hey, I kinda forgot how to get java on vscode so can someone remind me pweeeeese

**Comment by NinjaBob123** [comment]
Hey, sorry I just saw this
Go here

https://aka.ms/vscode-java-installer-win

That should install the things you need just follow the directions

**Comment by NinjaBob123** [comment]
And maybe here
vscode:extension/vscjava.vscode-java-pack

**Comment by NinjaBob123** [comment]
Not the second one

**Comment by NinjaBob123** [comment]
That should install the things you need just follow the directions

**Comment by NinjaBob123** [comment]
This also might be helpful once you get the other thing

vscode:extension/vscjava.vscode-java-pack

Or just look up "Extension Pack Java" in the extensions tab and install the one verified from microsoft.com

**Comment by NinjaBob123** [comment]
Or just look up "Extension Pack Java" in the extensions tab and install

**Comment by NinjaBob123** [comment]
Or just look up "Extension Pack Java" in the extensions tab and install

**Comment by NinjaBob123** [comment]
I updated it

**Comment by NinjaBob123** [comment]
I updated it again

**Comment by NinjaBob123** [comment]
I know that this one i broken, i am trying to fix

**Comment by aremyarmsonmyhead** [comment]
Thanks for reminding me

**Comment by NinjaBob123** [comment]
ur welcome

**Comment by CalebBowser** [comment]
Hunter, your code is very long. Please make sure to add comments EVERYWHERE, not just in certain areas. I also tried it out and don't know if it actually works. If its not complete yet, you can totally still work on it

"U R a stinky beta" - From the mouth of James

**Pull request merged**
